// Please understand that most of the documentation and docstring -
// - in this program was generated by AI for easier understanding debugging and troubleshooting.





// ── Time helpers (stateless, no class needed) ─────────────────────────────────

/**
 * Konverterer SSB timekode til vanlig tid
 * Støtter årlig (f.eks 2024) måndelig (f.eks 2024M01) kvarterer (f.eks 2024K1)
 * @param {string} code - SSB time kode string
 * @returns {number} Månede og år i en fin format.
 */
function codeToTimestamp(code) {
  const y    = parseInt(code);
  const tail = code.substring(4).replace(/\D+/, "");
  if (!tail)            return y * 12 + 11;
  const n = parseInt(tail);
  return tail.length === 1 ? y * 12 + (n * 3 - 1) : y * 12 + (n - 1);
}

/**
 * Converts the month based timestamp to a readable format.
 * @param {number} ts - Timestamp as returned by {@link codeToTimestamp}
 * @returns {string} Label in "Mon YYYY" format, e.g. "Jan 2024"
 */
function timestampToLabel(ts) {
  const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
  return months[ts % 12] + " " + Math.floor(ts / 12);
}

// ── SSBChart ──────────────────────────────────────────────────────────────────
// Owns one chart panel: its table, metadata, UI controls, and Chart.js instance.

/**
 * Manages a single chart panel: SSB metadata, UI dimension controls, and the Chart.js instance.
 * Multiple instances are distinguished by a DOM ID suffix (e.g. "" and "_2").
 */
class SSBChart {

  /**
   * @param {string} suffix - DOM ID suffix to distinguish multiple instances (e.g. "" or "_2")
   * @param {string} initialTable - SSB table ID to load on startup (e.g. "14092")
   */
  constructor(suffix, initialTable) {
    this.suffix   = suffix;
    this.table    = initialTable;
    this.metadata = null;
    this.chart    = null;
  }

  // ── Getters for DOM elements ------------------------------------------------

  /**
   * Returns the DOM element whose ID is `id + this.suffix`.
   * @param {string} id - Base element ID (without suffix)
   * @returns {HTMLElement|null}
   */
  get(id)        { return document.getElementById(id + this.suffix); }

  /**
   * Returns the current value of the DOM element with the given base ID.
   * @param {string} id - Base element ID (without suffix)
   * @returns {string|undefined}
   */
  getVal(id)     { return this.get(id)?.value; }

  // ── Unit extracted from metadata -------------------------------------------

  /**
   * The measurement unit of the currently selected content code, extracted from metadata.
   * Returns an empty string if metadata is not yet loaded or no unit is defined.
   * @type {string}
   */
  get unit() {
    const u = Object.values(this.metadata?.dimension?.ContentsCode?.category?.unit ?? {})[0];
    return u?.base || "";
  }

  // ── Metadata + UI population ------------------------------------------------

  /**
   * Fetches metadata for the given SSB table and populates time and dimension controls in the UI.
   * @param {string} [table=this.table] - SSB table ID to load (defaults to the current table)
   * @returns {Promise<void>}
   */
  async load(table = this.table) {
    this.table    = table;
    this.metadata = await fetch(
      `https://data.ssb.no/api/pxwebapi/v2/tables/${this.table}/metadata`
    ).then(r => r.json());
    this._populateTime();
    this._buildDimensions();
  }

  /**
   * Populates the start/end time dropdowns from metadata and defaults to the last 6 periods.
   * @private
   */
  _populateTime() {
    const times = Object.entries(this.metadata.dimension.Tid.category.label);
    const opts  = times.map(([v, t]) => `<option value="${v}">${t}</option>`).join("");
    ["Tid_start", "Tid_end"].forEach(id => this.get(id).innerHTML = opts);
    this.get("Tid_start").selectedIndex = Math.max(0, times.length - 6);
    this.get("Tid_end").selectedIndex   = times.length - 1;
  }

  /**
   * Builds and injects dimension `<select>` controls for all non-time dimensions in the metadata.
   * @private
   */
  _buildDimensions() {
    const container = this.get("dimensionControls");
    if (!container) return;
    const dims = this.metadata.dimension;
    container.innerHTML = Object.entries(dims)
      .filter(([name]) => name !== "Tid")
      .map(([name, dim]) => `
        <div class="dim">
          <label>${dim.label}</label>
          <select id="${name + this.suffix}">
            ${Object.entries(dim.category.label)
              .map(([v, t]) => `<option value="${v}">${t}</option>`).join("")}
          </select>
        </div>`).join("");
  }

  // ── Data fetching -----------------------------------------------------------

  /**
   * Reads the current UI control values and fetches the corresponding data from the SSB API.
   * Handles time range ordering (swaps start/end if reversed) and builds a human-readable series label.
   * @returns {Promise<{timestamps: number[], data: number[], seriesLabel: string, unit: string}>}
   */
  async fetch() {
    const dims = this.metadata.dimension;

    const contents = this.getVal("ContentsCode")
      ?? Object.keys(dims.ContentsCode.category.index)[0];

    const allTimes = Object.keys(dims.Tid.category.index);
    let s = allTimes.indexOf(this.getVal("Tid_start"));
    let e = allTimes.indexOf(this.getVal("Tid_end"));
    if (s > e) [s, e] = [e, s];

    let url = `https://data.ssb.no/api/pxwebapi/v2/tables/${this.table}/data?lang=no`
            + `&valueCodes[Tid]=${allTimes.slice(s, e + 1).join(",")}`
            + `&valueCodes[ContentsCode]=${contents}`;

    const parts = [];
    for (const [dimName, dim] of Object.entries(dims)) {
      if (dimName === "Tid") continue;
      const value = this.getVal(dimName) ?? Object.keys(dim.category.index)[0];
      if (!value) continue;
      if (dimName !== "ContentsCode") url += `&valueCodes[${dimName}]=${value}`;
      const lbl = dim.category.label[value];
      if (lbl) parts.push(lbl.split("(")[0].trim());
    }

    const json     = await fetch(url).then(r => r.json());
    const rawCodes = Object.keys(json.dimension.Tid.category.index);

    return {
      timestamps:  rawCodes.map(codeToTimestamp),
      data:        json.value,
      seriesLabel: parts.join(" - ") + (this.unit ? ` (${this.unit})` : ""),
      unit:        this.unit
    };
  }

  // ── Rendering --------------------------------------------------------------

  /**
   * Destroys the current Chart.js instance and clears the reference.
   */
  destroy() {
    this.chart?.destroy();
    this.chart = null;
  }

  /**
   * Renders a single-axis line chart onto the given canvas element.
   * Destroys any existing chart on this instance before rendering.
   * @param {string} canvasId - ID of the `<canvas>` element to render into
   * @param {{timestamps: number[], data: number[], seriesLabel: string, unit: string}} result - Fetch result from {@link fetch}
   */
  render(canvasId, result) {
    this.destroy();
    const ctx = document.getElementById(canvasId);
    if (!ctx) return;
    this.chart = new Chart(ctx, {
      type: "line",
      data: {
        labels:   result.timestamps.map(timestampToLabel),
        datasets: [SSBChart.makeDataset(result, "#3b82f6")]
      },
      options: SSBChart.singleOptions(result.unit)
    });
  }

  // ── Static chart helpers ---------------------------------------------------

  /**
   * Builds a Chart.js dataset config object from a fetch result.
   * @param {{data: number[], seriesLabel: string}} r - Fetch result
   * @param {string} color - CSS color string for the line and fill
   * @param {string} [yAxisID] - Y-axis ID for dual-axis charts (e.g. "y1" or "y2")
   * @returns {object} Chart.js dataset configuration object
   */
  static makeDataset(r, color, yAxisID) {
    return {
      label:           r.seriesLabel,
      data:            r.data,
      tension:         0.3,
      borderColor:     color,
      backgroundColor: color + "33",
      pointRadius:     3,
      ...(yAxisID && { yAxisID, spanGaps: true })
    };
  }

  /**
   * Returns Chart.js options for a single-series, single-axis line chart.
   * @param {string} unit - Unit label used for the Y-axis title and tooltip
   * @returns {object} Chart.js options object
   */
  static singleOptions(unit) {
    return {
      responsive: true, maintainAspectRatio: false,
      plugins: {
        legend: { display: true },
        tooltip: { callbacks: { label: c => `${c.dataset.label}: ${c.parsed.y?.toLocaleString()} ${unit}` } }
      },
      scales: {
        x: { title: { display: true, text: "Tid" } },
        y: { title: { display: true, text: unit || "Verdi" } }
      }
    };
  }
}

// ── Dashboard ─────────────────────────────────────────────────────────────────
// Owns two SSBChart instances and handles compare mode + UI visibility.

/**
 * Top-level controller that owns two {@link SSBChart} instances and orchestrates
 * single-view, dual-view, and compare-overlay rendering modes.
 */
class Dashboard {
  /**
   * Initializes both chart instances with the default SSB table (14092).
   */
  constructor() {
    this.chart1      = new SSBChart("",   "14092");
    this.chart2      = new SSBChart("_2", "14092");
    this.compareChart = null;
  }

  /**
   * Loads metadata for both charts in parallel.
   * @returns {Promise<void>}
   */
  async init() {
    await Promise.all([this.chart1.load(), this.chart2.load()]);
  }

  // ── Visibility helper -------------------------------------------------------

  /**
   * Shows or hides a DOM element by ID using `display: block / none`.
   * @param {string} id - Element ID
   * @param {boolean} visible - Whether to show the element
   */
  show(id, visible) {
    document.getElementById(id).style.display = visible ? "block" : "none";
  }

  // ── Run button -------------------------------------------------------------

  /**
   * Fetches data for the active charts and renders them according to the current UI toggle state.
   * Handles three modes: single chart, dual chart side-by-side, and dual-axis compare overlay.
   * @returns {Promise<void>}
   */
  async run() {
    const showSecond = document.getElementById("toggleChart2").checked;
    const compare    = document.getElementById("toggleCompare").checked;

    const r1 = await this.chart1.fetch();
    const r2 = (showSecond || compare) ? await this.chart2.fetch() : null;

    this.chart1.destroy();
    this.chart2.destroy();
    this.compareChart?.destroy();
    this.compareChart = null;

    const chart1Card = document.getElementById("chart1").closest(".chart-card");

    if (compare && r2) {
      chart1Card.style.display = "none";
      this.show("chart2Card",       false);
      this.show("chartCompareCard", true);
      this._renderCompare(r1, r2);
    } else {
      this.show("chartCompareCard", false);
      chart1Card.style.display = "block";
      this.chart1.render("chart1", r1);
      this.show("chart2Card", showSecond && !!r2);
      if (showSecond && r2) this.chart2.render("chart2", r2);
    }
  }

  // ── Compare rendering -------------------------------------------------------

  /**
   * Renders a dual-axis overlay line chart merging two series onto a shared time axis.
   * Each series gets its own Y-axis (left/right) and color. Missing data points are shown as gaps.
   * @param {{timestamps: number[], data: number[], seriesLabel: string, unit: string}} r1 - First series
   * @param {{timestamps: number[], data: number[], seriesLabel: string, unit: string}} r2 - Second series
   * @private
   */
  _renderCompare(r1, r2) {
    const ctx = document.getElementById("chartCompare");
    if (!ctx) return;

    const allTs = [...new Set([...r1.timestamps, ...r2.timestamps])].sort((a, b) => a - b);
    const map1  = Object.fromEntries(r1.timestamps.map((ts, i) => [ts, r1.data[i]]));
    const map2  = Object.fromEntries(r2.timestamps.map((ts, i) => [ts, r2.data[i]]));

    const d1 = { ...r1, data: allTs.map(ts => map1[ts] ?? null) };
    const d2 = { ...r2, data: allTs.map(ts => map2[ts] ?? null) };
    const [unit1, unit2] = [r1.unit || "Verdi", r2.unit || "Verdi"];

    this.compareChart = new Chart(ctx, {
      type: "line",
      data: {
        labels:   allTs.map(timestampToLabel),
        datasets: [SSBChart.makeDataset(d1, "#3b82f6", "y1"), SSBChart.makeDataset(d2, "#f59e0b", "y2")]
      },
      options: {
        responsive: true, maintainAspectRatio: false,
        interaction: { mode: "index", intersect: false },
        plugins: {
          legend: { display: true },
          tooltip: { callbacks: { label: c => {
            if (c.parsed.y === null) return null;
            return `${c.dataset.label}: ${c.parsed.y.toLocaleString()} ${c.datasetIndex === 0 ? unit1 : unit2}`;
          }}}
        },
        scales: {
          x:  { title: { display: true, text: "Tid" } },
          y1: { position: "left",  title: { display: true, text: unit1, color: "#3b82f6" }, ticks: { color: "#3b82f6" }, grid: { color: "#33415580" } },
          y2: { position: "right", title: { display: true, text: unit2, color: "#f59e0b" }, ticks: { color: "#f59e0b" }, grid: { drawOnChartArea: false } }
        }
      }
    });
  }

  // ── Toggle handlers (called from HTML) -------------------------------------

  /**
   * Shows or hides the second chart's controls when its toggle checkbox changes.
   * @param {HTMLInputElement} cb - The checkbox element
   */
  onToggleChart2(cb) {
    document.getElementById("controls_2").style.display = cb.checked ? "block" : "none";
  }

  /**
   * Ensures the second chart is enabled when compare mode is turned on.
   * @param {HTMLInputElement} cb - The compare toggle checkbox element
   */
  onToggleCompare(cb) {
    if (cb.checked) {
      document.getElementById("toggleChart2").checked = true;
      document.getElementById("controls_2").style.display = "block";
    }
  }

  /**
   * Reloads the metadata for chart1 or chart2 when the user selects a new SSB table.
   * @param {string} suffix - Chart suffix ("" for chart1, "_2" for chart2)
   * @param {string} value - New SSB table ID
   * @returns {Promise<void>}
   */
  async onTableChange(suffix, value) {
    const chart = suffix === "" ? this.chart1 : this.chart2;
    await chart.load(value);
  }
}

// ── Bootstrap ─────────────────────────────────────────────────────────────────
const dashboard = new Dashboard();
dashboard.init();

// Thin global shims so HTML onclick= attributes still work
const handleFetch      = ()       => dashboard.run();
const onToggleChart2   = cb       => dashboard.onToggleChart2(cb);
const onToggleCompare  = cb       => dashboard.onToggleCompare(cb);
const onTableChange    = (s, v)   => dashboard.onTableChange(s, v);
